# Generated by Django 5.0.4 on 2024-04-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('dp', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
