# Generated by Django 5.0.4 on 2024-04-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_feedback_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategories',
            old_name='name',
            new_name='image',
        ),
        migrations.AddField(
            model_name='servicecategories',
            name='catename',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
