# Generated by Django 5.0.4 on 2024-04-09 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_name_servicecategories_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('duration', models.FloatField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Services')),
                ('available', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.servicecategories')),
            ],
        ),
    ]
