# Generated by Django 5.0.4 on 2024-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
