# Generated by Django 5.0.4 on 2024-04-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_services_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
