# Generated by Django 5.0.4 on 2024-04-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_services_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
