# Generated by Django 5.0.4 on 2024-04-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_courceinquiry_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='timings',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
